# Generated by Django 2.1.3 on 2018-12-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fortniteskins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('first_seen', models.DateField()),
                ('outfit_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('date', models.DateField()),
                ('season_theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fortniteskins',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season'),
        ),
    ]
