# Generated by Django 2.1.3 on 2018-11-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fortniteskins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.IntegerField()),
                ('rarity', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('outfit_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
