# Generated by Django 2.1.3 on 2018-12-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('season_theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='fortniteskins',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.season'),
        ),
    ]
